//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowXAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos_Equipos
    {
        public int ID { get; set; }
        public int Equipo_ID { get; set; }
        public int Proyectos_ID { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
