//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlowXAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tareas()
        {
            this.Tareas1 = new HashSet<Tareas>();
        }
    
        public int ID { get; set; }
        public int Proyecto_ID { get; set; }
        public Nullable<int> TareaPadre_ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FInicio { get; set; }
        public Nullable<System.DateTime> Ffin { get; set; }
        public Nullable<System.DateTime> FfinEsperado { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> EsSubtarea { get; set; }
        public int Responsable_ID { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tareas> Tareas1 { get; set; }
        public virtual Tareas Tareas2 { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
